name: cg_playground-py38

dependencies:
  - python==3.8.1
  - opencv==4.2.0
  - numpy>=1.11.0
  - pytest
  - pytest-mock>=1.10
  - conda-wrappers
  - esss_fix_format
  - pip:
      - imgui[full]

environment:
  PYTHONPATH:
    - {{ root }}/src