name: cg_playground-py36

dependencies:
  - python>=3.6
  - numpy>=1.11.0
  - pytest
  - pytest-mock>=1.10
  - conda-wrappers
  #- esss_fix_format
  # we also need pyimgui, but you'll need to install it with:
  # pip install imgui[full]

environment:
  PYTHONPATH:
    - {{ root }}/src